# Site settings
name: PopLau
email: ghpopst@icoud.com
author: PopLau
url: http://poplau.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/poplau/
baseurl: ''
description: 种一棵树最好的时间是十年前，其次是现在。
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: This is motto.
banner: 种一棵树最好的时间是十年前，其次是现在。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: poplau
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

